name: CI

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: []
        platform: []
        arch: []
        include:
        - os: "ubuntu-latest"
          platform: "linux"
          target: "zip"
          arch: "x64"
        - os: "ubuntu-latest"
          platform: "linux"
          target: "deb"
          arch: "x64"
        - os: "ubuntu-latest"
          platform: "linux"
          target: "zip"
          arch: "arm64"
        - os: "ubuntu-latest"
          platform: "linux"
          target: "deb"
          arch: "arm64"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: yarn run make --platform ${{ matrix.platform }} --target ${{ matrix.target }} --arch ${{ matrix.arch }}