name: CI

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        arch: ["x64", "arm64"]
        platform: ["linux"]
        target: ["deb", "rpm"]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: yarn run make --platform ${{ matrix.platform }} --target ${{ matrix.target }} --arch ${{ matrix.arch }}